<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns:og="http://ogp.me/ns#">
<head>
<link rel="stylesheet" href="${resource(dir:'css',file:'skin.css')}" />

<script type="text/javascript"
	src="${resource(dir:'js',file:'jquery.jcarousel.min.js')}"></script>
<script type="text/javascript">

jQuery(document).ready(function() {
    jQuery('#mycarousel').jcarousel();
	scroll: 1
});

</script>
<meta name="layout" content="dinerotaxiCompanyAccountEmployeeL" />

</head>
<body>
	
<div class="mainContent">

	<div class="con">
    	
        <div class="content mt10">        	
            
        	<div class="bOX725">
            
            	<h1>Terminos y condiciones en DineroTaxi</h1>
                
               	<p>Estas son las Condiciones Generales de Contratación que regulan la relación contractual por la que los usuarios de Internet acceden a los contenidos y servicios que DineroTaxi . (en adelante DineroTaxi.com) pone a su disposición a través del sitio www.dinerotaxi.com, en adelante dinerotaxi.com (el Sitio), y/o su aplicación para teléfonos inteligentes o <em>smartphones (</em>la Aplicación Móvil). El Sitio es operado por DineroTaxi, con sede legal en Manuel Ugarte 3883 13 B, Ciudad de Buenos Aires.</p>
		<p>DineroTaxi ha preparado el presente a fin de informar a los usuarios de los términos y condiciones en virtud de los cuales los servicios disponibles a través del Sitio y la Aplicación Móvil son prestados. Los servicios del Sitio, la Aplicación Móvil y los mensajes de texto y de notificación PUSH enviados por DineroTaxi son prestados únicamente a fin de asistir a los usuarios a (i) obtener información sobre taxis y conductores de taxis; y (ii) conectar a los usuarios con los conductores de taxis, a fin de que aquéllos puedan contratar a éstos, mediante el acceso a opiniones de terceros, y mediante el envío de comunicaciones entre usuarios y conductores de taxis a través de una o más empresas de Radio Taxis.</p>
		<p>Se deja expresa constancia que: (a) las opiniones y graduaciones o puntajes de los conductores son meras estadásticas recibidas por información de terceros y que en ningún caso es la opinión de DineroTaxi, sobre asuntos relativos a taxis, y para ningún otro propósito; y (b) DineroTaxi, en relación a la contratación de viajes, presta únicamente el servicio de conectar a los usuarios con las empresas correspondientes de Radio  Taxis, y a través de ellas con los conductores, no pudiendo entenderse en ningún caso que: (a) DineroTaxi provee el servicio de contratación de viajes; y/o (b) DineroTaxi provee servicios de Radio  Taxi. Los términos & Nosotros , Nuestra, la Sociedad, y DineroTaxi, se refieren en todo momento a DineroTaxi. El término qué Usted se refiere al usuario visitando el Sitio y/o la Aplicación Móvil, utilizando los servicios del Sitio y/o la Aplicación Móvil y/o contribuyendo información al Sitio y/o a la Aplicación Móvil.</p>
		<p>Los servicios se encuentran disponibles para los usuarios bajo la condición de que Usted acepta sin ninguna reserva todos y cada uno de los Términos y Condiciones y las notificaciones que se realicen en virtud de ellos (todos ellos, conjuntamente, considerados el Contrato). Usted acepta estar sujeto al Contrato mediante el acceso o el uso del Sitio y/o la Aplicación Móvil, bajo cualquier forma. Por lo tanto, Usted debe leer los términos del Contrato cuidadosamente. En caso que Usted considere que no puede aceptar todos los términos y condiciones aquí­ establecidos, le solicitamos se abstenga de utilizar el Sitio, la Aplicación Móvil y/o los servicios brindados por el mismo, dado que su uso podrá ser considerado no autorizado por DineroTaxi.</p>
		<p>Uso del Sitio y de la Aplicación Móvil.</p>
		<p>Es condición que el uso del Sitio que Usted garantiza lo siguiente al momento de usarlo:</p>
		<p>(i) Usted tiene o es mayor a 21 años de edad a la fecha de registro de una cuenta en el Sitio; o si Usted es o era menor a 21 años, habí­a obtenido el consentimiento de sus padres o de quienes tengan la patria potestad al momento de registrar una cuenta;</p>
		<p>(ii) Usted posee la capacidad legal para suscribir y ejecutar el Contrato y para usar el Sitio de conformidad con todos los términos y condiciones aquí­ establecidos; y</p>
		<p>(iii) Usted garantiza que toda la información por Usted provista al Sitio es precisa, actual, completa y veraz y que será Usted (y nadie más que Usted), quien use su cuenta, que nosotros supervisaremos, y que Usted será completamente responsable por el uso de su cuenta por cualquier otra persona diferente de Usted.</p>
		<h3 class="mt10">Información sobre Menores de Edad</h3>
		<p>Nosotros no recabamos en forma intencional información sobre menores de edad.</p>
		<h3 class="mt10">Derechos respecto al uso del Sitio y/o  de la Aplicación Móvil</h3>
		<p>DineroTaxi se reserva el derecho, a su sola discreción, a denegar acceso al Sitio, la Aplicación Móvil y/o a los servicios que ofrecemos, en cualquier momento y por cualquier razón, incluyendo, pero sin limitarse a ello, en virtud de una violación a este Contrato.</p>
		<p>La transmisión, reproducción, copia, publicación, o redistribución del contenido del Sitio, la Aplicación Móvil o una parte de ambas o algunas de ellas, bajo cualquier modo, se encuentra estrictamente prohibida sin el previo consentimiento escrito de DineroTaxi. Para obtener dicho permiso, por favor contacte a la compaí­a en la siguiente dirección: info@dinerotaxi.com.</p>
		<p>Nuestro objetivo es actualizar en forma regular el contenido y las funcionalidades del Sitio y la Aplicación Móvil y por lo tanto podemos cambiar ambos o alguno de ellos en cualquier momento. Cuando lo considere necesario, DineroTaxi puede suspender el acceso al Sitio o a la Aplicación Móvil o cerrar una o ambas definitivamente. Debe tenerse en cuenta que el material disponible en el Sitio y/o la Aplicación Móvil puede estar desactualizado en cualquier momento y que no tenemos obligación alguna, excepto por lo dispuesto en la Ley de Protección de Datos Personales, y sus normas regulatorias, cuando sean aplicables, a actualizar dichos contenidos.</p>
		<h3 class="mt10">Actividades Prohibidas</h3>
		<p>La información y contenido del Sitio y/o de la Aplicación Móvil (incluyendo, pero sin limitarse a ello, mensajes, información, datos, textos, música, sonidos, fotos, gráficos, videos, mapas, í­conos, software, códigos o cualquier otro material), así­ como la infraestructura utilizada para proveer dicho contenido e información, es propiedad de DineroTaxi. Usted acepta no modificar, copiar, distribuir, transmitir, mostrar, reproducir, publicar, otorgar licencias, transferir, vender o revender ninguna información, software, productos o servicios obtenidos desde o a través del Sitio, o la Aplicación Móvil, o de mensajes de texto enviados por DineroTaxi.</p>
		<p>Asimismo, Usted acepta no:</p>
		<p>(i) utilizar este Sitio, la Aplicación Móvil o su contenido para cualquier propósito comercial;</p>
		<p>(ii) acceder, monitorear o copiar cualquier contenido o información del Sitio y/o de la Aplicación Móvil utilizando un robot, scraper, o cualquier otro medio automático o proceso manual para cualquier fin sin nuestro expreso permiso escrito;</p>
		<p>(iii) violar las restricciones de cualquier encabezado excluyendo robots en el Sitio y/o la Aplicación Móvil o evitar cualquier otra medida utilizada para prevenir o limitar acceso al Sitio y/o la Aplicación Móvil;</p>
		<p>(iv) realizar cualquier acción que imponga, o pueda imponer, conforme nuestra opinión discrecional, una carga irrazonable o desproporcionada en nuestra infraestructura;</p>
		<p>(v) enlace directo a cualquier parte del Sitio por cualquier razón sin nuestro expreso consentimiento escrito;</p>
		<p>(vi) frame, mirror o de cualquier otro modo incorporar una parte o todo el Sitio dentro de cualquier otro sitio sin nuestro previo expreso consentimiento; o</p>
		<p>(vii) intentar modificar, traducir, adaptar, editar, desensamblar, descompilar o realizar ingenierí­a inversa cualquier programa de software utilizado por DineroTaxi en relación con el Sitio, la Aplicación Móvil o los servicios prestados.</p>
		<h3 class="mt10">Polí­tica de Privacidad</h3>
		<p>El uso de los servicios disponibles a través del Sitio, o mediante su teléfono móvil, implica su aceptación y consentimiento para que nosotros procesemos información personal, y su garantí­a de que todo contenido proveí­do por Usted es correcto.</p>
		<p>La Política de Privacidad de DineroTaxi en relación al uso del Sitio y la Aplicación Móvil se encuentra en un documento separado en el Sitio bajo el título Política de Privacidad.</p>
		<p>Por favor tenga en cuenta que la información personal que Usted transmita al Sitio y/o la Aplicación Móvil será utilizada de acuerdo a nuestra Política de Privacidad.</p>
		<h3 class="mt10">Utilización de otras áreas interactivas (críticas y comentarios)</h3>
		<p>Se le aconseja notar que mediante el enví­o de contenido al Sitio y/o a la Aplicación Móvil mediante mensajes de texto, mail, postings en el Sitio o por cualquier medio, incluyendo crí­ticas y comentarios sobre taxis y conductores de taxis, preguntas, comentarios, sugerencias, ideas o similares contenidas en cualquier enví­o (todos ellos, conjuntamente, Enví­os), Usted otorga a DineroTaxi un derecho no exclusivo, libre de regalí­as, perpetuo transferible, irrevocable y total para (a) usar, reproducir, modificar, adaptar, traducir, publicar, crear trabajos derivados de, y mostrar públicamente y realizar cualquier Enví­o en todo el mundo a través de cualquier medio existente o a crearse; y (b) usar el nombre que Usted enví­a en conexión con ese Enví­o. Usted acepta y declara conocer que DineroTaxi puede, a su sola discreción, optar o no por atribuir sus comentarios o crí­ticas.</p>
		<p>Asimismo, Usted otorga a DineroTaxi el derecho a llevar adelante acciones legales contra cualquier persona o entidad que viole sus derechos o los de DineroTaxi en los Enví­os en virtud de un incumplimiento de este Contrato. Usted conoce y acepta que los Enví­os no son confidenciales, y que Usted no posee ningún derecho de propiedad sobre los mismos. DineroTaxi no edita o controla los Mensajes de Usuarios mostrados (posteados) o distribuidos en el Sitio incluyendo, aquellos recibidos mediante mensajes de texto, salas de chat, boletines informativos o cualquier otro foro de comunicación, y no será bajo ningún concepto responsable u obligado por dichos Mensajes de Usuarios.</p>
		<p>El Sitio y/o la Aplicación Móvil pueden incluir foros de discusión, boletines, servicios de crí­ticas u otros fórums en los cuales Usted o terceros pueden mostrar (postear) crí­ticas sobre experiencias en taxis u otro contenido, mensajes, materiales u otros elementos del Sitio . Si DineroTaxi provee dichas íreas Interactivas, Usted será el único responsable por su uso, y las usará a su propio riesgo. Mediante el uso de las áreas Interactivas, Usted expresamente acepta no mostrar (postear), subir (upload), transmitir, distribuir, guardar, crear o de cualquier modo publicar mediante el Sitio lo siguiente:</p>
		<p>(i) cualquier mensaje, dato, texto, música, fotos, gráficos, códigos o cualquier otro material (Contenido) que sea falso, ilegal, engañoso, calumnioso, injurioso, difamatorio, obsceno, pornográfico, indecente, sugestivo, acosador, o que provoque acosamiento, amenazante, invasivo de la privacidad, abusivo, fraudulento u objetable de cualquier otro modo;</p>
		<p>(ii) Contenido que sea ofensivo a la comunidad online, tal como contenido que provoque racismo, discriminación por cualquier razón, odio, o daño fí­sico o moral de cualquier tipo hacia cualquier grupo o persona;</p>
		<p>(iii) Contenido que constituya, promocione, incite o provea instrucciones para una conducta ilegal, un delito penal, cree una contingencia civil, viole los derechos de cualquier persona en cualquier paí­s del mundo, o que de cualquier otra forma cree una contingencia o viole una ley municipal, local, provincial, nacional o internacional;</p>
		<p>(iv) Contenido que provea instrucciones para realizar actividades ilegales tales como hacer o comprar armas ilegales, violar la privacidad de las personas, o proveer o crear virus informáticos;</p>
		<p>(v) Contenido que viole una patente, marca, diseño industrial, secreto industrial o cualquier otro derecho de propiedad intelectual o industrial de cualquier persona. En particular, contenido que promueva una copia ilegal o no autorizada de los derechos intelectuales o industriales de cualquier otra persona, tales como proveer programas piratas de computación o links hacia los mismos, proveer información para evitar el funcionamiento de sistemas de protección anti @“ copias, o preveer música o links hacia música cuya transmisión no fue autorizada o licenciada;</p>
		<p>(vi) Contenido que produzca confusión en cuanto a la afiliación de Usted con una persona o entidad, incluyendo DineroTaxi;</p>
		<p>(vii) Promociones no solicitadas, mailings masivos o spams, transmisión de correo no deseado, cadenas de correo, campaña polí­tica, propaganda o comerciales, rifas, etc;</p>
		<p>(viii) Contenido conteniendo actividad comercial y/o ventas sin nuestro previo consentimiento, tales como concursos, sorteos, trueques, o esquemas de inversión piramidal;</p>
		<p>(ix) Información privada de cualquier persona, incluyendo, sin limitación, apellido, domicilios, números de teléfono, dirección de mail y número de tarjetas de crédito;</p>
		<p>(x) Que contenga páginas restringidas al público o con acceso limitado con claves, o páginas ocultas o imágenes (aquellas sin links desde o hacia una página libremente accesible);</p>
		<p>(xi) Virus, información corrupta o cualquier otro tipo de documentos o files destructivos;</p>
		<p>(xii) Contenido que no tenga relación con el tema del área Interactiva en la cual dicho contenido es mostrado (posteado);</p>
		<p>(xiii) Contenido o links a contenido que, a sola discreción de DineroTaxi, (a) viola cualquiera de los acápites anteriores; (b) es cuestionable; (c) restringe o inhibe a cualquier persona para usar o disfrutar las áreas Interactivas o el Sitio; o (d) pueda exponer a DineroTaxi o sus usuarios a un daño o contingencia de cualquier tipo.</p>
		<p>Nosotros no asumimos responsabilidad alguna por el Contenido mostrado (posteado), guardado o subido (uploaded) por Usted o por cualquier usuario, o por cualquier pérdida o daño que dicho contenido pueda provocar, ni es DineroTaxi responsable por errores, difamaciones, calumnias, omisiones, falsedades, obscenidades, pornografí­a o palabras soeces que Usted pueda encontrar. Como un proveedor de servicios interactivos, DineroTaxi no es responsable por las declaraciones, opiniones o Contenido enviado por los usuarios en los foros públicos, la página personal o cualquier otra área Interactiva.</p>
		<p>A pesar que DineroTaxi no tiene obligación alguna de monitorear, editar o controlar de modo alguno el Contenido mostrado (posteado) o distribuido mediante cualquier área Interactiva, DineroTaxi se reserva el derecho, y tendrá completa discrecionalidad para ejercerlo, a remover, controlar y/o editar sin notificación alguna cualquier Contenido mostrado (posteado) o guardado en el Sitio y/o la Aplicación Móvil en cualquier momento y por cualquier razón, y Usted es el único responsable de crear copias de respaldo o reemplazar cualquier Contenido que Usted muestre (postee) o guarde en el Sitio y/o la Aplicación Móvil a su costo.</p>
		<p>Si se determina que Usted posee derechos morales al Contenido (incluyendo derechos de atribución o integridad), Usted declara por el presente que: (a) no requiere que se utilice información personal que lo identifique en relación al Contenido, o cualquier trabajo derivado del mismo, o sus mejoras o actualizaciones; (b) no tiene objeciones a la publicación, uso, modificación, borrado y explotación del Contenido por DineroTaxi, o sus licenciatarios y sucesores bajo cualquier tí­tulo; (c) renuncia a perpetuidad y acuerda no efectuar reclamo alguno en relación o afirmar cualquier derecho a derechos morales de autor en el Contenido; y (d) renuncia a toda acción que pudiera tener frente a DineroTaxi, sus licenciatarios y sucesores bajo cualquier tí­tulo en virtud de dichos derechos morales.</p>
		<p>El uso de las áreas Interactivas o cualquier servicio brindado por el Sitio y/o la Aplicación Móvil en violación de mencionado en este apartado, constituye una violación a los Términos y Condiciones del Sitio y puede resultar, entre otros, en la rescisión o suspensión de sus derechos a usar las áreas Interactivas y/o el Sitio y/o la Aplicación Móvil. A fin de cooperar con requerimientos legales de autoridades gubernamentales, órdenes judiciales, o para proteger los sistemas de DineroTaxi o sus usuarios, o para asegurar la integridad de la operación de los negocios y sistemas de DineroTaxi, DineroTaxi puede acceder y revelar cualquier información que considere apropiada o necesaria, incluyendo, sin limitarse a ello, la información del perfil del usuario (nombre, dirección de correo electrónico, etc), direcciones de IP, información respecto al tráfico de datos, historia del uso del Sitio y/o de la Aplicación Móvil, y Contenido mostrado (posteado), por el usuario. El derecho de DineroTaxi a revelar cualquier información tenga prevalencia sobre cualquiera de los términos de la Polí­tica de Privacidad. Se deja constancia que DineroTaxi, en relación con la información protegida por la Ley de Protección de Datos Personales, ejercerá sus derechos bajo el presente en cumplimiento de la misma y de sus regulaciones.</p>
		<h3 class="mt10">Responsabilidad de DineroTaxi</h3>
		<p>La información, software, productos y servicios publicados en el Sitio y/o la Aplicación Móvil pueden incluir errores e inexactitudes. DineroTaxi no garantiza la exactitud de, y se libera de toda responsabilidad por, cualquier error o inexactitud relativa la información y descripción de un taxi o de un taxista en el Sitio o enviada a los usuarios a un teléfono móvil.</p>
		<p>Cualquier comentario u otros materiales mostrados (posteados) no están destinados a ser un asesoramiento basado en el cual se pueda tomar decisiones. Asimismo, El Sitio y/o la Aplicación Móvil no efectúa recomendaciones de tipo legal o personal y los contenidos vertidos en los mismos no deben ser tomados como consejos o soluciones de í­ndole legal o de ninguna otra í­ndole por parte de Usuarios o visitantes. Por lo tanto, DineroTaxi no será responsable por ningún daño que resulte de la toma de decisiones por parte del Usuario o cualquier visitante del Sitio y/o usuario de la Aplicación Móvil, o cualquier tercero que hubiere conocido la información mostrada en el Sitio y/o en la Aplicación Móvil, basada en dicha información.</p>
		<p>DineroTaxi no realiza declaración u otorga garantí­a alguna sobre la adecuación de la información, software, productos y servicios contenidos en el Sitio y/o la Aplicación Móvil (el Contenido del Sitio ), o cualquier parte del mismo, para cualquier fin en particular, y la inclusión u ofrecimiento de productos o servicios en el Sitio y/o la Aplicación Móvil no constituye una recomendación de dichos productos o servicios por DineroTaxi. Dicho Contenido del Sitio y/o de la Aplicación Móvil se presenta conforme fuera obtenido de los Usuarios, y no incluye ninguna garantí­a de ningún tipo.</p>
		<p>La información contenida en el Sitio y/o la Aplicación Móvil proviene de varias fuentes, entre las que se cuentan los propios Usuarios del Servicio. Dicha información no puede considerarse exhaustiva, completa, o que satisfará todas las necesidades del Usuario. En su gran mayorí­a, esa información está meramente destinada a permitir al Usuario el acceso a una mayor cantidad de datos sobre el tema de su interés, los que generalmente son provistos por terceros, sin un efectivo control por parte del Titular, por lo que se sugiere al Usuario que lea con especial cuidado estos Términos y Condiciones, sin perjuicio de lo cual se reserva el derecho de bloquear el acceso o de eliminar cualquier comunicación o material que considere: a) abusivo, difamatorio, obsceno, falso o engañoso, b) violatorio de propiedad intelectual de un tercero, o c) violatorio de las disposiciones contenidas en el presente documento.</p>
		<p>DineroTaxi no realiza declaración alguna en relación a que el Sitio, la Aplicación Móvil, sus servidores o cualquier mail o contenido enviado por DineroTaxi se encuentran libres de virus u otros componentes dañosos. Hasta el máximo lí­mite permitido por la ley, DineroTaxi se libera de responsabilidad y no realiza declaración u otorga garantí­a alguna en relación con la información, software, productos y servicios, incluyendo cualquier declaración o garantí­a sobre sus condiciones de comercialización, capacidad para cumplir un propósito determinado, y su titularidad.</p>
		<p>DineroTaxi tampoco realiza declaración o garantí­a alguna sobre la exactitud del Contenido del Sitio y/o la Aplicación Móvil.</p>
		<p>Ninguno de los presentes Términos y Condiciones puede excluir o limitar la responsabilidad de DineroTaxi por (i) muerte y daños personales causados por negligencia; (ii) fraude; (iii) dolo o culpa grave; o (iv) cualquier responsabilidad que no puede ser excluida conforme a la ley.</p>
		<p>Sujeto a lo establecido anteriormente, Usted acuerda usar el Sitio, la Aplicación Móvil y recibir el contenido a su propio riesgo y bajo ninguna circunstancia DineroTaxi (sus directores, gerentes, apoderados y afiliadas) serán responsables por cualquier daño o pérdida directa, indirecta, casual, mediata o inmediata, daño moral, lucro cesante, pérdida de datos, contratos, dinero o cualquier tipo de daño, o en cualquier forma relacionada con su capacidad de acceso a este Sitio y/o la Aplicación Móvil, su uso, su incapacidad de acceso a uno o ambos de ellos o una demora en el mismo, y el posteo de Contenido (incluyendo, sin limitarse a ello, la toma de decisiones basada en las opiniones que aparezcan en el Sitio y/o en la Aplicación Móvil; virus, información, software, enlaces, productos, y servicios obtenidos a través del Sitio y/o la Aplicación Móvil, o existentes en virtud de su acceso a, uso de, y posteo de información en el Sitio y/o la Aplicación Móvil).</p>
		<p>Los Términos y Condiciones y las limitaciones y exclusiones de responsabilidad descriptas anteriormente no afectan derechos leales que no puedan ser excluidos bajo la legislación vigente. La limitación de responsabilidad descripta anteriormente meramente refleja la atribución de riesgos que acepta cada parte de este Contrato.</p>
		<p>En relación a la contratación de los viajes, se deja nuevamente expresa constancia que DineroTaxi no es un intermediario entre los usuarios y los conductores de taxis, sino que se limita a proveer la infraestructura de comunicación para conectar a los usuarios con las empresas de Radio “ Taxi. En tal sentido:</p>
		<p>(a) DineroTaxi no es una empresa de Radio  Taxi;</p>
		<p>(b) Los conductores de taxis no están afiliados a DineroTaxi:</p>
		<p>(c) DineroTaxi no se responsabiliza por los problemas, daños y/o perjuicios que puedan ocasionarse en los viajes, ni presta garantí­a alguna respecto del buen funcionamiento de los taxis ni el comportamiento de los conductores de los mismos; y</p>
		<p>(d) Los tiempos de espera para viajes y los tiempos informados para el trayecto del viaje en sí­ son estimados informados por los propios conductores y los promedios según el dí­a, hora y tráfico regular que existe en un determinado trayecto, y respectivamente. Eventuales retrasos, ya sea por parte del conductor del taxi al recoger pasajeros, o demoras en el trayecto del taxi, no son responsabilidad de DineroTaxi, quien se limita a transmitir información proveí­da por otros.</p>
		<h3 class="mt10">Indemnidad</h3>
		<p>Mediante el uso de este Sitio y/o de la Aplicación Móvil, y por lo tanto aceptando los Términos y Condiciones, Usted acepta defender y mantener indemne a DineroTaxi y todos sus empleados, directores, gerentes y agentes de y contra cualquier acción, reclamo, demanda, pérdida, daños, multa, penalidades u otros costos de cualquier tipo incluyendo pero sin limitarse a honorarios razonables contables y legales, iniciados por terceros como resultado de:</p>
		<p>i. el incumplimiento del Usuario de este Contrato o los documentos relacionados con el presente;</p>
		<p>ii. el incumplimiento del Usuario de cualquier ley o los derechos de un tercero; o</p>
		<p>iii. el uso de este Sitio y/o de la Aplicación Móvil.</p>
		<h3 class="mt10">Enlaces a sitios de terceros</h3>
		<p>El Sitio contiene enlaces a sitios operados por terceros no relacionados con DineroTaxi.</p>
		<p>Dichos enlaces se proveen como referencia únicamente. Nosotros no controlamos dichos sitios y no aceptamos responsabilidad por su contenido, sus polí­ticas de privacidad u otras prácticas de dichos sitios, o cualquier pérdida o daño resultante del uso de dichos sitios. Asimismo, es responsabilidad del Usuario asegurarse que los enlaces que Usted seleccione o el software que baje (download) (ya sea de este Sitio u otros) sea libre de virus, defectos, troyanos, u otros elementos de naturaleza destructiva. La inclusión de enlaces a dichos sitios no implica nuestra conformidad con el contenido de dichos sitios ni asociación alguna con sus operadores. En ciertos casos a Usted puede ofrecérsele en un sitio de un tercero unir (link) su perfil en DineroTaxi con un perfil en un sitio de un tercero. Elegir hacerlo es completamente opcional por su parte, y la decisión de permitir ese link puede deshacerse (con el sitio del tercero), en cualquier momento.</p>
		<h3 class="mt10">Enlaces desde sitios de terceros</h3>
		<p>Usted puede proveer enlaces al Sitio, siempre y cuando lo realice de una manera legal y que no dañe nuestra reputación o se aproveche de ella, pero no puede proveer enlaces de una forma tal que induzca a terceros a considerar que existe cualquier forma de asociación, aprobación o soporte por parte nuestra a su sitio cuando ello no exista. Nuestro Sitio no puede ser replicado en cualquier otro sitio, ni tampoco puede Usted proveer un enlace a cualquier parte de nuestro Sitio que no sea su página principal (homepage). Nos reservamos el derecho a retirar la autorización a proveer enlace en cualquier momento y sin notificación alguna. El sitio desde el cual Usted provee enlace a nuestro Sitio debe cumplir con todos los estándares de contenido establecidos en estos Términos y Condiciones.</p>
		<h3 class="mt10">Derechos de propiedad intelectual</h3>
		<p>Todos los contenidos del Sitio y/o de la Aplicación Móvil y sus marcas son de titularidad de DineroTaxi. Nosotros no somos responsables por el contenido de sitios operados por terceros distintos a DineroTaxi.</p>
		<p>DineroTaxi, el logo del taxi y todo otro nombre de productos o servicios mostrados en el Sitio son propiedad de DineroTaxi, o de sus proveedores o licenciatarios, y no pueden ser copiados, imitados o usados, en forma parcial o total, sin la previa autorización escrita de DineroTaxi o el titular de los derechos intelectuales correspondiente. Adicionalmente, el estilo y diseño del Sitio, incluyendo todos los tí­tulos, fonts, headers, gráficos, í­conos, es propiedad intelectual de DineroTaxi y no pueden ser copiados, imitados o usados, en forma parcial o total, sin la previa autorización escrita de DineroTaxi.</p>
		<p>Todas las restantes marcas, marcas registradas, nombres de productos y nombres de sociedades mencionados en el Sitio y/o en la Aplicación Móvil son propiedad de sus respectivos dueños. La referencia a cualquier producto, servicio, proceso u otra información, por nombre comercial, marca, proveedores, u otros no constituyen ni implican un esponsoreo, apoyo o recomendación por parte de DineroTaxi. Otros logos y productos y nombres de compañí­as mencionadas aquí­ son de titularidad de sus respectivos dueños.</p>
		<h3 class="mt10">Polí­tica sobre contenido ilegal</h3>
		<p>DineroTaxi opera bajo el modo  notificación y borrado. Agradeceremos por lo tanto nos contacte en forma inmediata si tiene una queja u objeción al material o contenido que encuentre en el Sitio y/o en la Aplicación Móvil. Esto incluye mensajes de usuarios posteados en uno o ambos de ellos, o también si Usted considera que el material o contenido del Sitio y/o de la Aplicación Móvil implica una violación a derechos de propiedad intelectual que Ud. posee. DineroTaxi realizará sus mejores esfuerzos para remover dicho contenido ilegal en un plazo razonable.</p>
		<h3 class="mt10">Virus, Hackers y otros delitos</h3>
		<p>Usted no debe introducir virus, troyanos, bombas lógicas u otros materiales maliciosos o tecnológicamente perjudiciales para el Sitio y/o para la Aplicación Móvil. Usted no debe intentar tener acceso no autorizado a nuestro Sitio y/o a la Aplicación Móvil, al servidor donde nuestro Sitio se encuentra guardado o cualquier servidor, computadora o base de datos conectada a nuestro Sitio y/o a nuestra Aplicación Móvil. Usted no debe atacar nuestro Sitio y/o nuestra Aplicación Móvil via a ataque mal intencionado o un ataque DDOS.</p>
		<p>Si Usted incumple esta obligación, podrí­a incurrir en un delito, y lo notificaremos a las autoridades correspondientes, con quienes cooperaremos para su identificación. En caso de un incumplimiento, su derecho a utilizar el Sitio y la Aplicación Móvil cesará inmediatamente. No seremos responsables por cualquier pérdida o daño provocado por un ataque DDOS, virus u otros materiales dañinos tecnológicos que puedan infectar su computadora, programas, datos u otro material de su propiedad debido al uso de nuestro Sitio y/o Aplicación Móvil o debido a que Usted baje (download) cualquier material allí­ incluido, o en un sitio cuyo enlace se encuentre en cualquiera de ellos.</p>
		<p>Modificaciones al Sitio y/o a la Aplicación Móvil</p>
		<p>DineroTaxi puede modificar, agregar o borrar estos Términos y Condiciones o una parte de ellos en cualquier momento, a su sola discreción, cuando lo considere necesario por razones legales, regulatorias o técnicas, o debido a cambios en los servicios prestados o en la naturaleza o diseño del Sitio y/o la Aplicación Móvil.</p>
		<p>Usted, por lo tanto, acuerda estar sujeto a los Términos y Condiciones modificados. DineroTaxi puede modificar, suspender o discontinuar cualquier aspecto del servicio prestado a través del Sitio y/o de la Aplicación Móvil en cualquier momento, incluyendo la disponibilidad de algún servicio particular, la base de datos o el contenido. DineroTaxi también puede imponer lí­mites a ciertos servicios o restringir su acceso a todo o parte del Sitio y/o de la Aplicación Móvil, o cualquier otro sitio de DineroTaxi o sus afiliadas, sin notificación previa y sin que ello otorgue derecho a compensación alguna, por razones técnicas o de seguridad, a fin de prevenir contra accesos no autorizados, pérdidas de, o destrucción de datos o cuando consideremos a nuestra entera discreción que Usted está incumpliendo cualquiera de los presentes Términos y Condiciones, o por una ley o regulación o cuando decidiere discontinuar un servicio determinado.</p>
		<p>Algunas de las provisiones de los Términos y Condiciones pueden ser derogadas por provisiones o noticias publicadas en otros lugares del Sitio y/o en la Aplicación Móvil. El uso continuado por su parte del Sitio y/o de la Aplicación Móvil ahora o con posterioridad a la publicación de dicha notificación de cambios indicará su aceptación a dichas modificaciones.</p>
		<h3 class="mt10">Contacto de Emergencia  Términos y Condiciones</h3>
		<p>Los clientes de DineroTaxi acuerdan que sus contactos de emergencia están autorizados a ver los detalles del último mensaje enviado a DineroTaxi y que el contacto de emergencia está autorizado a pasar dicha información a la policí­a. Los clientes de DineroTaxi deben asegurarse que sus contactos de emergencia están al tanto de los Términos y Condiciones de DineroTaxi y le recomendamos que les provean una copia de los mismos para asegurarse que están de acuerdo con ellos. En todos los casos, DineroTaxi considerará que mediante el registro del contacto de emergencia como tal, podemos recolectar y usar su información personal de acuerdo a lo establecido en nuestra Polí­tica de Privacidad.</p>
		<h3 class="mt10">Jurisdicción/Términos Generales</h3>
		<p>El Sitio es operado por una sociedad argentina y el Contrato será regulado por las normas de la República Argentina. Mediante el acceso y el uso de los servicios disponibles en el Sitio y/o de la Aplicación Móvil, Usted consiente con la jurisdicción de los Tribunales Comerciales Ordinarios de la Capital Federal de la República Argentina. Usted acuerda asimismo que todo reclamo que pueda ser realizado contra DineroTaxi relativos al acceso, uso o de cualquier otro modo relacionados con el Sitio y/o con la Aplicación Móvil será resuelto por los tribunales antes indicados. El uso del Sitio y/o de la Aplicación Móvil no está autorizado en jurisdicciones en los cuales no puedan ejecutarse los presentes Términos y Condiciones, incluyendo, sin limitación, las provisiones de este párrafo. Lo anteriormente establecido no se aplicará en la medida que la ley aplicable en su paí­s de residencia requiere aplicación de otra ley y ello no puede excluirse por contrato. Usted acuerda asimismo que no existe entre Usted y DineroTaxi una relación de agencia, sociedad o empleo como resultado del presente Contrato o del uso del Sitio y/o de la Aplicación Móvil.</p>
		<p>La ejecución del presente Contrato por nuestra parte está sujeta a las leyes y procesos legales aplicables, y nada de lo aquí­ establecido puede limitar nuestro derecho a cumplir con requerimientos de las autoridades legales relativos al uso del Sitio y/o de la Aplicación Móvil por Usted o información obtenida por nosotros relativa a dicho uso.</p>
		<p>En caso que cualquier disposición de este Contrato fuera declarada ilegal, nula, inaplicable o sin efecto, por cualquier tribunal competente, las demás disposiciones no se verán afectadas y seguirán en plena vigencia y mantendrán sus efectos. Las Partes harán sus mayores esfuerzos para sustituir cualquier disposición que haya sido declarada ilegal, nula, inaplicable o sin efecto, por otra disposición que sea lo más semejante posible y de similar naturaleza, pero que sea legalmente exigible.</p>
		<p>Este Contrato constituye el acuerdo completo celebrado entre las Partes y deja sin efecto cualquier convenio o documento firmado con anterioridad entre las Partes, así­ como cualquier correspondencia, conversaciones y negociaciones anteriores en relación con su objeto. Una versión impresa de este Contrato, o de cualquier notificación basada en o relativa a este Contrato, realizada en forma electrónica será admisible en procedimientos judiciales o administrativos con los mismos alcances y en las mismas condiciones que cualquier contrato comercial.</p>
		<p>Cualquier derecho no otorgado expresamente en el presente es reservado por la Sociedad.</p>
                                    
            </div>
         
         </div>
         
         <!-- SIDEBAR -->
            
 
        <div class="sidebar mt10">
            
                
			<!--  g:render template="/template/recomenda" /-->
                
			<g:render template="/template/shareFacebook" />
            
            </div>
    
    </div>

</div>

</body>
</html>
